# See the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/examples/transform-amd-to-commonjs-example/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "15:00"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 1
